'use strict';
/**
 * MySQL / PostgreSQL 方言层测试（纯字符串翻译，确定性，无数据库依赖）+
 * 适配器构造与 fail-fast 校验（连接池惰性建连，无需真实服务）。
 * 真实库集成冒烟由 SMOKE_DATABASE_URL 门控（见文件尾说明）。
 */
const test = require('node:test');
const assert = require('node:assert');

const {
  dialectFromUrl,
  translateDdl,
  translateStatement,
  translateSqlFor,
  pgParams,
  isPragma,
  listTablesSql,
  tableColumnsSql,
  getDbAdapter,
  resetDbAdaptersForTest,
} = require('../dist/index.js');

// ---------------------------------------------------------------------------
// dialectFromUrl
// ---------------------------------------------------------------------------

test('dialectFromUrl：scheme 识别与归一', () => {
  assert.strictEqual(dialectFromUrl('mysql://u:p@h:3306/db'), 'mysql');
  assert.strictEqual(dialectFromUrl('mariadb://u@h/db'), 'mysql');
  assert.strictEqual(dialectFromUrl('postgres://u@h/db'), 'postgres');
  assert.strictEqual(dialectFromUrl('postgresql://u@h/db'), 'postgres');
  assert.strictEqual(dialectFromUrl('file:./x.db'), null);
  assert.strictEqual(dialectFromUrl('libsql://x.turso.io'), null);
  assert.strictEqual(dialectFromUrl(''), null);
});

// ---------------------------------------------------------------------------
// DDL 翻译
// ---------------------------------------------------------------------------

const SAMPLE_DDL =
  'CREATE TABLE IF NOT EXISTS accounts (' +
  'id TEXT PRIMARY KEY, name TEXT, score REAL, n INTEGER PRIMARY KEY AUTOINCREMENT, created DATETIME)';

test('translateDdl(mysql)：TEXT 主键→VARCHAR(255)、AUTOINCREMENT、REAL→DOUBLE', () => {
  const out = translateDdl(SAMPLE_DDL, 'mysql');
  assert.match(out, /id VARCHAR\(255\) PRIMARY KEY/);
  assert.match(out, /name TEXT(?!\s+PRIMARY)/, '普通 TEXT 列保留');
  assert.match(out, /n INT AUTO_INCREMENT PRIMARY KEY/);
  assert.match(out, /score DOUBLE/);
});

test('translateDdl(postgres)：identity 列、TEXT 主键保留', () => {
  const out = translateDdl(SAMPLE_DDL, 'postgres');
  assert.match(out, /id TEXT PRIMARY KEY/);
  assert.match(out, /n INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
});

test('translateDdl：datetime(\'now\') 按方言替换', () => {
  const sql = "CREATE TABLE t (ts DATETIME DEFAULT datetime('now'))";
  assert.match(translateDdl(sql, 'mysql'), /DEFAULT CURRENT_TIMESTAMP/);
  assert.match(translateDdl(sql, 'postgres'), /DEFAULT now\(\)/);
  assert.match(translateDdl(sql, 'sqlite'), /datetime\('now'\)/, 'sqlite 原样');
});

test('translateDdl：BLOB → PG BYTEA', () => {
  assert.match(translateDdl('CREATE TABLE t (b BLOB)', 'postgres'), /BYTEA/);
});

// ---------------------------------------------------------------------------
// DML 翻译
// ---------------------------------------------------------------------------

test('translateStatement(mysql)：INSERT OR IGNORE → INSERT IGNORE', () => {
  const out = translateStatement("INSERT OR IGNORE INTO t (a) VALUES (?)", 'mysql');
  assert.match(out, /INSERT IGNORE INTO t/);
});

test('translateStatement(mysql)：ON CONFLICT DO UPDATE → ON DUPLICATE KEY UPDATE + VALUES(col)', () => {
  const out = translateStatement(
    'INSERT INTO tenant_quotas (tenant_id, qps) VALUES (?, ?) ON CONFLICT(tenant_id) DO UPDATE SET qps=excluded.qps, updated_at=excluded.updated_at',
    'mysql'
  );
  assert.match(out, /ON DUPLICATE KEY UPDATE/);
  assert.match(out, /qps=VALUES\(qps\)/);
  assert.match(out, /updated_at=VALUES\(updated_at\)/);
  assert.doesNotMatch(out, /excluded\./);
});

test('translateStatement(postgres)：INSERT OR IGNORE 追加 ON CONFLICT DO NOTHING', () => {
  const out = translateStatement('INSERT OR IGNORE INTO t (a) VALUES (?)', 'postgres');
  assert.match(out, /^INSERT INTO t \(a\) VALUES \(\?\) ON CONFLICT DO NOTHING$/);
  // 显式 upsert 不重复追加
  const out2 = translateStatement(
    'INSERT INTO q (id, v) VALUES (?, ?) ON CONFLICT(id) DO UPDATE SET v=excluded.v',
    'postgres'
  );
  assert.strictEqual((out2.match(/ON CONFLICT/g) || []).length, 1, '已有 ON CONFLICT 不重复追加');
});

test('pgParams：? 顺序编号，单引号字面量内跳过', () => {
  assert.strictEqual(pgParams('a = ? AND b = ?'), 'a = $1 AND b = $2');
  assert.strictEqual(pgParams("msg = 'what?' AND a = ?"), "msg = 'what?' AND a = $1");
});

test('translateSqlFor：一站式（PG 含占位符，MySQL 不改占位符）', () => {
  assert.strictEqual(translateSqlFor('a=?', 'postgres', true), 'a=$1');
  assert.strictEqual(translateSqlFor('a=?', 'mysql', true), 'a=?');
});

// ---------------------------------------------------------------------------
// 杂项与适配器构造（fail-fast / 惰性建连，无需真实服务）
// ---------------------------------------------------------------------------

test('isPragma 与 splitSqlStatements', () => {
  assert.strictEqual(isPragma('PRAGMA journal_mode=WAL'), true);
  assert.strictEqual(isPragma('SELECT 1'), false);
});

test('listTablesSql / tableColumnsSql：三方言统一 name 列', () => {
  for (const d of ['sqlite', 'mysql', 'postgres']) {
    const t = listTablesSql(d);
    assert.match(t.sql, /AS name/i, `${d} 表发现应含 name 别名`);
    const c = tableColumnsSql(d, 't1');
    if (d === 'sqlite') {
      assert.match(c.sql, /^PRAGMA table_info/i, 'sqlite 列信息走 PRAGMA');
    } else {
      assert.match(c.sql, /AS name/i, `${d} 列信息应含 name 别名`);
    }
  }
});

test('getDbAdapter：mysql/postgres 配置缺失或不匹配时 fail-fast', () => {
  resetDbAdaptersForTest();
  const oldBackend = process.env.DB_BACKEND;
  const oldUrl = process.env.DATABASE_URL;
  try {
    delete process.env.DATABASE_URL;
    assert.throws(() => getDbAdapter({ backend: 'mysql' }), /DATABASE_URL/);
    assert.throws(() => getDbAdapter({ backend: 'postgres' }), /DATABASE_URL/);
    // scheme 不匹配同样 fail-fast（数据落错库比启动失败更难收拾）
    assert.throws(
      () => getDbAdapter({ backend: 'mysql', url: 'postgres://u@h/db' }),
      /DATABASE_URL/
    );
  } finally {
    if (oldBackend === undefined) delete process.env.DB_BACKEND;
    else process.env.DB_BACKEND = oldBackend;
    if (oldUrl === undefined) delete process.env.DATABASE_URL;
    else process.env.DATABASE_URL = oldUrl;
    resetDbAdaptersForTest();
  }
});

test('getDbAdapter：合法 DATABASE_URL 惰性建连（无需真实服务）+ 单例', () => {
  resetDbAdaptersForTest();
  const oldBackend = process.env.DB_BACKEND;
  const oldUrl = process.env.DATABASE_URL;
  try {
    const a = getDbAdapter({ backend: 'mysql', url: 'mysql://u:p@127.0.0.1:3306/nope' });
    const b = getDbAdapter({ backend: 'mysql', url: 'mysql://u:p@127.0.0.1:3306/nope' });
    assert.strictEqual(a, b, '同 URL 单例');
    assert.strictEqual(a.cacheKey.startsWith('mysql:'), true);
    const p = getDbAdapter({ backend: 'postgres', url: 'postgres://u:p@127.0.0.1:5432/nope' });
    assert.strictEqual(p.cacheKey.startsWith('postgres:'), true);
    // PG prepare 的 ?→$n 在语句级生效（不触发连接）
    const stmt = p.prepare('SELECT * FROM t WHERE a = ?');
    assert.ok(typeof stmt.all === 'function');
  } finally {
    if (oldBackend === undefined) delete process.env.DB_BACKEND;
    else process.env.DB_BACKEND = oldBackend;
    if (oldUrl === undefined) delete process.env.DATABASE_URL;
    else process.env.DATABASE_URL = oldUrl;
    resetDbAdaptersForTest();
  }
});

/*
 * 真实库集成冒烟（可选，需要 MySQL/PG 实例）：
 *   SMOKE_MYSQL_URL=mysql://root:pass@localhost:3306/ah_smoke node --test test/db-dialect.test.cjs
 *   SMOKE_PG_URL=postgres://postgres:pass@localhost:5432/ah_smoke ...
 * 冒烟内容（见 scripts/smoke-db.cjs）：全 store 建表自愈 + db-copy sqlite→目标库 搬迁 + 行数校验。
 */
