/**
 * SQL 方言层（MySQL / PostgreSQL 支持）。
 *
 * 职责：把仓库内 store 层的 SQLite 方言 SQL 在适配器出口翻译为目标方言，
 * store 层代码零改动。覆盖面 = 项目实际使用的 SQL 形态（简单 DDL + 参数化 DML）：
 *   - DDL：TEXT PRIMARY KEY（MySQL TEXT 不能做主键 → VARCHAR(255)）、
 *     AUTOINCREMENT、BLOB、datetime('now')；
 *   - DML：INSERT OR IGNORE、ON CONFLICT(...) DO UPDATE SET（excluded.col）；
 *   - PG 占位符：? → $1..$n（跳过单引号字面量内的 ?）。
 * 明确不翻译：窗口函数、CTE、复杂子查询（仓库内不存在）。
 */

export type SqlDialect = 'sqlite' | 'mysql' | 'postgres';

/** 从 DATABASE_URL 的 scheme 判断方言；非 mysql/pg 协议返回 null。 */
export function dialectFromUrl(url: string): SqlDialect | null {
  const m = /^(mysql|mariadb|postgres|postgresql):\/\//i.exec(url.trim());
  if (!m || !m[1]) return null;
  const scheme = m[1].toLowerCase();
  if (scheme === 'mysql' || scheme === 'mariadb') return 'mysql';
  return 'postgres';
}

/** MySQL 下 TEXT 列不能做主键/唯一键（需指定键长），统一替换为 VARCHAR(255)。
 * PG 的 TEXT 主键合法且更优，不做改写。 */
export function translateDdl(sql: string, dialect: SqlDialect): string {
  if (dialect === 'sqlite') return sql;
  let out = sql;
  if (dialect === 'mysql') {
    out = out.replace(/\bTEXT\b(\s+(?:PRIMARY\s+KEY|UNIQUE)\b)/gi, 'VARCHAR(255)$1');
    out = out.replace(/\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi, 'INT AUTO_INCREMENT PRIMARY KEY');
    out = out.replace(/\bREAL\b/gi, 'DOUBLE');
  } else {
    // PostgreSQL：INTEGER PRIMARY KEY AUTOINCREMENT → identity 列
    out = out.replace(
      /\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b/gi,
      'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
    );
    out = out.replace(/\bBLOB\b/gi, 'BYTEA');
  }
  // datetime('now') 默认值
  if (dialect === 'mysql') out = out.replace(/datetime\('now'\)/gi, 'CURRENT_TIMESTAMP');
  else out = out.replace(/datetime\('now'\)/gi, 'now()');
  return out;
}

/** MySQL：ON CONFLICT(cols) DO UPDATE SET a=excluded.a,... → ON DUPLICATE KEY UPDATE a=VALUES(a),... */
function mysqlUpsert(sql: string): string {
  const ignore = /\bINSERT\s+OR\s+IGNORE\s+INTO\b/gi;
  const m = /\bON\s+CONFLICT\s*\(([^)]*)\)\s+DO\s+UPDATE\s+SET\s+([\s\S]+)$/i.exec(sql);
  if (!m || !m[2]) return sql.replace(ignore, 'INSERT IGNORE INTO');
  const setExprs = m[2].replace(/\bexcluded\.(\w+)/gi, 'VALUES($1)');
  const head = sql.slice(0, m.index).replace(ignore, 'INSERT IGNORE INTO');
  return `${head} ON DUPLICATE KEY UPDATE ${setExprs}`;
}

/** PG：? → $1..$n（跳过单引号字面量内的 ?）。 */
export function pgParams(sql: string): string {
  let out = '';
  let n = 0;
  let inString = false;
  for (let i = 0; i < sql.length; i++) {
    const ch = sql[i];
    if (ch === "'") {
      inString = !inString;
      out += ch;
      continue;
    }
    if (ch === '?' && !inString) {
      n += 1;
      out += `$${n}`;
      continue;
    }
    out += ch;
  }
  return out;
}

/** DML/DLL 语句级翻译（不含占位符改写；PG 占位符由调用方在绑定参数前做）。 */
export function translateStatement(sql: string, dialect: SqlDialect): string {
  if (dialect === 'sqlite') return sql;
  let out = translateDdl(sql, dialect);
  if (dialect === 'mysql') {
    out = mysqlUpsert(out);
  } else {
    // PostgreSQL：INSERT OR IGNORE → INSERT ... ON CONFLICT DO NOTHING（追加句尾）
    out = out.replace(/\bINSERT\s+OR\s+IGNORE\s+INTO\b/gi, 'INSERT INTO');
    if (/\bINSERT\s+INTO\b/i.test(out) && !/\bON\s+CONFLICT\b/i.test(out) && /^\s*INSERT/i.test(out)) {
      out = `${out.replace(/;\s*$/, '')} ON CONFLICT DO NOTHING`;
    }
  }
  return out;
}

/** 一站式翻译：DDL + DML +（PG）占位符。供适配器 exec/prepare 出口调用。 */
export function translateSqlFor(sql: string, dialect: SqlDialect, bindParams: boolean): string {
  const translated = translateStatement(sql, dialect);
  if (dialect === 'postgres' && bindParams) return pgParams(translated);
  return translated;
}

/** 是否 PRAGMA 语句（MySQL/PG 无对应，适配器降级为 no-op / 空结果）。 */
export function isPragma(sql: string): boolean {
  return /^\s*PRAGMA\b/i.test(sql);
}

/** 表发现 SQL（统一返回列别名 name）。 */
export function listTablesSql(dialect: SqlDialect): { sql: string; params: unknown[] } {
  if (dialect === 'mysql') {
    return {
      sql: "SELECT table_name AS name FROM information_schema.tables WHERE table_schema = DATABASE() AND table_type = 'BASE TABLE' ORDER BY table_name",
      params: [],
    };
  }
  if (dialect === 'postgres') {
    return {
      sql: "SELECT tablename AS name FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename",
      params: [],
    };
  }
  return {
    sql: "SELECT name AS name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name",
    params: [],
  };
}

/** 列信息 SQL（统一返回列别名 name，按 ordinal 排序）。 */
export function tableColumnsSql(dialect: SqlDialect, table: string): { sql: string; params: unknown[] } {
  if (dialect === 'mysql') {
    return {
      sql: 'SELECT column_name AS name FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = ? ORDER BY ordinal_position',
      params: [table],
    };
  }
  if (dialect === 'postgres') {
    return {
      sql: "SELECT column_name AS name FROM information_schema.columns WHERE table_name = $1 AND table_schema = 'public' ORDER BY ordinal_position",
      params: [table],
    };
  }
  return { sql: `PRAGMA table_info(${table})`, params: [] };
}

/** 按分号拆分（naive：不识别引号内分号；仓库内 DDL 无引号内分号）。 */
export function splitSqlStatements(sql: string): string[] {
  const out: string[] = [];
  for (const stmt of sql.split(/;\s*/)) {
    const trimmed = stmt.trim();
    if (trimmed) out.push(trimmed);
  }
  return out;
}
